version: '3'
services:
  adonis-test-postgres:
    image: postgres:12-alpine
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Test1234
      POSTGRES_USER: postgres
      POSTGRES_DB: adonis
    ports:
      - '5433:5432'
    networks:
      - adonis_test_internal

  adonis-test-redis:
    image: redis:alpine
    ports:
      - '6380:6379'
    volumes:
      - ./.data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - adonis_test_internal

networks:
  adonis_test_internal:
    external:
      name: adonis_test_internal
