version: '3'
services:
  adonis-postgres:
    image: postgres:12-alpine
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Test1234
      POSTGRES_USER: postgres
      POSTGRES_DB: adonis
    ports:
      - '5432:5432'
    networks:
      - adonis_internal

  adonis-redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./.data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - adonis_internal

networks:
  adonis_internal:
    external:
      name: adonis_internal
